# Diabetes Prediction

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

diabetes_df = pd.read_csv('./diabetes.csv')
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [3]:
diabetes_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
print("Number of zeros or unknown values for each attributes.")
print(f"Glucose: {(diabetes_df['Glucose'] == 0).sum()}")
print(f"BloodPressure: {(diabetes_df['BloodPressure'] == 0).sum()}")
print(f"SkinThickness: {(diabetes_df['SkinThickness'] == 0).sum()}")
print(f"Insulin: {(diabetes_df['Insulin'] == 0).sum()}")
print(f"BMI: {(diabetes_df['BMI'] == 0).sum()}")

Number of zeros or unknown values for each attributes.
Glucose: 5
BloodPressure: 35
SkinThickness: 227
Insulin: 374
BMI: 11

In [5]:
columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
diabetes_df[columns] = diabetes_df[columns].replace(0, np.nan)
diabetes_df[columns] = diabetes_df[columns].fillna(diabetes_df[columns].median())

In [6]:
print("Number of zeros or unknown values for each attributes.")
print(f"Glucose: {(diabetes_df['Glucose'] == 0).sum()}")
print(f"BloodPressure: {(diabetes_df['BloodPressure'] == 0).sum()}")
print(f"SkinThickness: {(diabetes_df['SkinThickness'] == 0).sum()}")
print(f"Insulin: {(diabetes_df['Insulin'] == 0).sum()}")
print(f"BMI: {(diabetes_df['BMI'] == 0).sum()}")

Number of zeros or unknown values for each attributes.
Glucose: 0
BloodPressure: 0
SkinThickness: 0
Insulin: 0
BMI: 0

In [7]:
columns_to_select = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", 'DiabetesPedigreeFunction', 'Outcome']
cleaned_diabetes_df = diabetes_df.loc[:, columns_to_select]
cleaned_diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Glucose                   768 non-null    float64
 1   BloodPressure             768 non-null    float64
 2   SkinThickness             768 non-null    float64
 3   Insulin                   768 non-null    float64
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Outcome                   768 non-null    int64
dtypes: float64(6), int64(1)
memory usage: 42.1 KB

In [8]:
cleaned_diabetes_df.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
0,148.0,72.0,35.0,125.0,33.6,0.627,1
1,85.0,66.0,29.0,125.0,26.6,0.351,0
2,183.0,64.0,29.0,125.0,23.3,0.672,1
3,89.0,66.0,23.0,94.0,28.1,0.167,0
4,137.0,40.0,35.0,168.0,43.1,2.288,1

In [9]:
from sklearn.model_selection import train_test_split

X = cleaned_diabetes_df.drop('Outcome', axis=1)
Y = cleaned_diabetes_df['Outcome']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, random_state=42, stratify=Y)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

logistic_model.fit(X_train, Y_train)
logistic_model.score(X_test, Y_test)

0.7272727272727273

In [12]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score

Y_pred = logistic_model.predict(X_test)
conf_matrix = confusion_matrix(Y_test, Y_pred)
print(conf_matrix)
print(accuracy_score(Y_test, Y_pred))
print(f1_score(Y_test, Y_pred))
print(precision_score(Y_test, Y_pred))
print(recall_score(Y_test, Y_pred))

[[84 16]
 [26 28]]
0.7272727272727273
0.5714285714285714
0.6363636363636364
0.5185185185185185

In [17]:
from logistic_regression import CustomLogisticRegression

custom_model = CustomLogisticRegression()
custom_model.fit(X_train, Y_train)
predictions = custom_model.predict(X_test)
print(list(predictions))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[np.float64(0.4841673560357087), np.float64(0.389387118968543), np.float64(0.500237484526967), np.float64(0.42865202813707826), np.float64(0.36716004979551103), np.float64(0.4138705222840828), np.float64(0.5254108327019135), np.float64(0.5954726989511714), np.float64(0.3862774101599363), np.float64(0.661989257898474), np.float64(0.4956807404005983), np.float64(0.5171803357638947), np.float64(0.4067595172685435), np.float64(0.4693838142524598), np.float64(0.43500287907318647), np.float64(0.4644460898867783), np.float64(0.5120854890255705), np.float64(0.36854277611601477), np.float64(0.5291048014917414), np.float64(0.4012554306202054), np.float64(0.42147570065436113), np.float64(0.714539677409675), np.float64(0.41814343964346296), np.float64(0.5762282416842948), np.float64(0.5021300746411198), np.float64(0.30101791865267885), np.float64(0.5858700086520835), np.float64(0.3457189091562694), np.float64(0.433536052385929), np.float64(0.3482848055084261), np.float64(0.3443002384893406), np.float64(0.37259176894438134), np.float64(0.4961946529065553), np.float64(0.6926496876005086), np.float64(0.62013604385957), np.float64(0.4481402300267953), np.float64(0.49840209589365225), np.float64(0.40064722941228426), np.float64(0.6294198192115231), np.float64(0.5239095123595723), np.float64(0.43551873399822827), np.float64(0.42064838652170977), np.float64(0.41212076954337323), np.float64(0.43830249939660604), np.float64(0.4372410399297561), np.float64(0.4633370136781008), np.float64(0.37629206718528324), np.float64(0.4180476221711169), np.float64(0.667618413286163), np.float64(0.47415490883578765), np.float64(0.4962630649710461), np.float64(0.5617373127058607), np.float64(0.5856120430811418), np.float64(0.37153059430468705), np.float64(0.5339753199939914), np.float64(0.5105169198053177), np.float64(0.5153345490280528), np.float64(0.4903716905324706), np.float64(0.5400904115793399), np.float64(0.4568228674897657), np.float64(0.6146591132695223), np.float64(0.49508419917914037), np.float64(0.3797934952857904), np.float64(0.5952597076476238), np.float64(0.3335980300449534), np.float64(0.4657801674998954), np.float64(0.5998701263158002), np.float64(0.3404455431306181), np.float64(0.49985530130613315), np.float64(0.5360560426176482), np.float64(0.4232502694724548), np.float64(0.376318201122121), np.float64(0.48866978277263373), np.float64(0.4664734230897385), np.float64(0.36397242769002125), np.float64(0.44193559543223304), np.float64(0.3743254714927693), np.float64(0.5539983459395289), np.float64(0.401390258833526), np.float64(0.35880696123939443), np.float64(0.36466570624512856), np.float64(0.47506303762653884), np.float64(0.3789442101451651), np.float64(0.4523108835096742), np.float64(0.3849936759216033), np.float64(0.34720687447436627), np.float64(0.48417265726541064), np.float64(0.5172582876067595), np.float64(0.3834704156477387), np.float64(0.5535517546995317), np.float64(0.5511582699207435), np.float64(0.6260277796837637), np.float64(0.3849066907318097), np.float64(0.4401276227464345), np.float64(0.5228407701971026), np.float64(0.4929492345168593), np.float64(0.6388146506148445), np.float64(0.5316135081960183), np.float64(0.5847264258879966), np.float64(0.36145398846059734), np.float64(0.39537630948549823), np.float64(0.5039109489513744), np.float64(0.494209186946895), np.float64(0.37911668680283245), np.float64(0.5553655392158333), np.float64(0.4619589928461512), np.float64(0.7875830304622746), np.float64(0.4670568256292015), np.float64(0.5703997081222574), np.float64(0.43826290361460196), np.float64(0.5423991777761906), np.float64(0.6040065643615626), np.float64(0.5821519511044305), np.float64(0.508342021309238), np.float64(0.5012648040657279), np.float64(0.43943018911986775), np.float64(0.4791529880576368), np.float64(0.35500269127194783), np.float64(0.5538260015893156), np.float64(0.40083812231244226), np.float64(0.7736491399009802), np.float64(0.34434422461878983), np.float64(0.44353144796642996), np.float64(0.5710942171444285), np.float64(0.4879934592243807), np.float64(0.5410951507423918), np.float64(0.5512515199276092), np.float64(0.5276226194190569), np.float64(0.4020112184282971), np.float64(0.4083808560581296), np.float64(0.3931659810936077), np.float64(0.5604027642728109), np.float64(0.4473607283528501), np.float64(0.5978332565543512), np.float64(0.5875555428317306), np.float64(0.38270772580286894), np.float64(0.3908994838549458), np.float64(0.3300696828140915), np.float64(0.3516026238950962), np.float64(0.4024879838288193), np.float64(0.3554829409177425), np.float64(0.4271131948817554), np.float64(0.41765006801674615), np.float64(0.356083804708365), np.float64(0.31069683288182764), np.float64(0.46040339649829726), np.float64(0.4566726276864788), np.float64(0.527837661714953), np.float64(0.49789204118455627), np.float64(0.295309786219296), np.float64(0.3861802029948553), np.float64(0.390715215103453), np.float64(0.64666235320502), np.float64(0.4126035044974099)]